name: "Elixir coverage feedback"
description: "Action to run tests, check coverage, and send a feedback message to the pull request."

branding:
  icon: "message-square"
  color: "purple"

inputs:
  github_token:
    description: "GitHub token"
    required: true
  coverage_tool:
    description: "Coverage tool"
    default: "default"
    required: false
  coverage_threshold:
    description: “Coverage threshold”
    default: 90
    required: false

runs:
  using: "composite"
  steps:
    - name: Tests and coverage
      id: tests
      shell: bash
      run: if mix test --cover 2>&1 | tee coverage_report.log; then echo 'success running the tests'; fi
    - name: Feedback comment
      uses: actions/github-script@v5
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const actionPath = '${{ github.action_path }}';
          const coverageTool = '${{ inputs.coverage_tool }}'.toLowerCase();

          const script = require(`${actionPath}/script.js`);
          await script({
            core,
            github,
            context,
            coverageTool,
            coverageThreshold: ${{ inputs.coverage_threshold }},
          });
